#
# Copyright 2016-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0
#

jvm.resource.tracing=true

# Controls the display of warning messages when a resource is discarded.
# Setting this property to false enables warnings to be shown when a resource is discarded.
disable.discard.warning=false

# Enables the use of JVM safepoints to facilitate profiling and debugging.
# Safepoints are synchronization points in the program where threads can be paused. This property is useful for detecting performance issues and analyzing thread behavior.
jvm.safepoint.enabled=true

# Automatically closes resources that have not been properly closed and logs a warning message.
# This property is intended primarily for debugging. It closes any resources that have not been properly closed and logs a warning message.
warnAndCloseIfNotClosed=true

# Disables the logging of announcements by the chronicle component.
# Setting this property to true turns off the logging functionality of the chronicle announcer. This can be helpful in reducing log clutter if the announcer messages are not necessary.
chronicle.announcer.disable=true

# Enables the detection and reporting of unoptimized operations.
# When this property is set to true, the system actively checks for operations that are not optimized and generates a report. This is beneficial for identifying potential areas for performance improvement.
report.unoptimised=true
